trigger: none

pool:
  name: Default

steps:

- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'hinz-vega-sc-dev'
    subscriptionId: '4aeae9ec-76bf-4564-b099-a2c5805aa2a1'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'hinz-vega-test-1'
    location: 'East US'
    templateLocation: 'Linked artifact'
    csmFile: 'azuredeploy.json'
    csmParametersFile: 'azuredeploy.parameters.json'
    deploymentMode: 'Incremental'